### ISSUE TITLE
Crashes immediately on CyanogenMod 11 KitKat 4.4.4

### ISSUE THREAD

**Issue by scumola** [gabm/FancyPlaces#1]
Crashes immediately. No debugging output. Downloaded from fossdroid.

**Comment by gabm** [comment]
Thank u for your bug report!

I will investigate this further as by now i did not have a look yet into compatibility for <=4.4. Maybe I'll contact you for further debugging!

**Comment by scumola** [comment]
No problem.  Let me know if you need me to test something.  I'm at: bigwebb@gmail.com

**Comment by jojorb** [comment]
As well on GT-I9300 OmniRom 4.4.4 - great app idea tho

**Comment by gabm** [comment]
I think I found the problem - Its probably an API Call that requires API=>21...

would you please try this [version](https://www-user.tu-chemnitz.de/~gabm/FancyPlaces/FancyPlaces.apk) and report back?

**Comment by gabm** [comment]
potential fix in commit 93c9f52f685e6b73358acd47d31e22160ad16446

**Comment by jojorb** [comment]
hi there,
well now i can see the title and the big tick, but still no localisation and rendering on map,
and no list of saving item nor pictures, :/

**Comment by scumola** [comment]
That was it.  Works like a charm now on KitKat 4.4.4!  Woohoo!

**Comment by gabm** [comment]
Hi Roby,

as your issue seems to be a bit different, would u please open a new issue and describe your problem a but more in detail? (which buttons are u pressing, what is supposed to happen and what happens?) thx!
