### ISSUE TITLE
Usability improvement: visual clue that clicking on photo will crete a foto

### ISSUE THREAD

**Issue by k3b** [gabm/FancyPlaces#10]
If you open an existing fancy-place-item and click on the foto nothing happens.

If you open an existing fancy-place-item, click edit and click on the foto you can take a new foto.

It would be great to have a visual clue if the foto is clickable

**Comment by gabm** [comment]
I fixed this issue by adding a camera button instead of making the image itself clickable, will be released with v1.2.0
