### ISSUE TITLE
delete a saved place

### ISSUE THREAD

**Issue by anandcoral** [gabm/FancyPlaces#17]
How can I delete a saved place ?
There is 'Edit' menu option but no "Delete" option.

Please guide.

Anand

**Comment by gabm** [comment]
hey anand, there should be an option when long-clicking a fancy place in the list...

**Comment by nogweii** [comment]
It would be more intuitive to be see the share and delete buttons in the details view. I generally see apps moving away from long presses, as they are not discoverable outside of trial and error. (As exemplified by this ticket.) Would you accept a patch to move them?

**Comment by gabm** [comment]
of course i would accept patches. It's just that currently i don't have time to work in FP though :/
