### ISSUE TITLE
mapquest tiles, api policy change

### ISSUE THREAD

**Issue by GavelRust** [gabm/FancyPlaces#23]
Giebn the mapquest tile access api change breaking this fine app do have plans to change provider,  use new api, or 

(mobile isnt showing text apologize if typos)

**Comment by GavelRust** [comment]
^ given the

**Comment by gabm** [comment]
Thank you for your bugreport - I changed the default map source to mapnik as MapQuest shuts down its free service - please expect the new version in some hours on f-droid

**Comment by gabm** [comment]
The new version is live for some weeks - it works very well
