### ISSUE TITLE
Update to API lvl 23+

### ISSUE THREAD

**Issue by gabm** [gabm/FancyPlaces#24]
- add support for permissions at runtime

**Comment by k3b** [comment]
@gabm  i am currently working on making the app compatible with android-10 in https://github.com/k3b/FancyPlaces

* done: remove .idea files from git
* added gradle wrapper to project.

curent work in progress

* replace com.melnykov:floatingactionbutton:1.3.0 with FloatingActionButton from com.android.support:design
  * melnykov:floatingactionbutton is no longer supported and not compatible with recent android-sdk version.
* move LocationHandler(gps)-logic from Applicaton to activity neccessary to implement Ask-for-permission
* implement Ask-for-permission for LocationHandler(gps)-logic
* upgrade to newer osmdroid lib version and fix api-signatur changes
* upgrade to api-28
* convert dependencies to androidx
* add travis continuous build.

I have already done this conversion for https://github.com/k3b/LocationMapViewer.

I hope you accept my merge request when done.....

**Comment by k3b** [comment]
could this be closed because of https://github.com/gabm/FancyPlaces/pull/27 ?

**Comment by gabm** [comment]
fixed by #27
