### ISSUE TITLE
no geolocalisation in app

### ISSUE THREAD

**Issue by jojorb** [gabm/FancyPlaces#6]
the phone is a GT-I9300 Galaxy S III
App Version is 1.0-DEBUG
no google services

when click on the + icon
i can edit the title and i see the tick icon.
i can take a picture 
when i click on update location it show "updating location" but nothing happened, nothing shown on map..
i can edit Notes,
then i click on the Tick to save my title , my pic my notes, (with world map)
i finally click on the left arrow .
nothing shown on list or map
and no result on update location

**Comment by gabm** [comment]
Thanks a lot for ur detailed bug report!

It turns out that your issue regarding localization in the absence of google play services has been already reported by another user in Issue #2...

I will therefore close this issue as a duplicate, please follow issue #2 to be up to date...
