### ISSUE TITLE
Support for multiple selection in ListView

### ISSUE THREAD

**Issue by gabm** [gabm/FancyPlaces#8]
We need support for multiple selection of FancyPlaces for export to gpx or other file-formats as well...

**Comment by k3b** [comment]
if this feature is only for the export to gpx then it may be easier to add a menueitem "export all to gpx"

**Comment by gabm** [comment]
well yes and no - i think its also one step towards "multiple delete", "multiple sharing" (e.g. email) or after the necessary redesign "manually sorting", maybe even grouping one day...

**Comment by gabm** [comment]
this has been implemented now, still fine-tuning the result but it should be ok now - next step: GPX Export...
