### ISSUE TITLE
Cannot get GPS data if gps was off on programmstart

### ISSUE THREAD

**Issue by k3b** [gabm/FancyPlaces#9]
getting gps only works if gps was on before programmstart.
it does not work if gps is activated after programmstart

Possible cause: gps-listeners are not re-initialized in OnResume

to reproduce:
- kill FancyPlyces in TaskManager
- Switch off gps
- start FancyPlyces
- Switch on gps
- SwitchBack to FancyPlaces
  - ==> FancyPlyces will not get gps-notification (no gps-icon in status bar). Restarting FancyPlyces does not help
    becauses it is still in memory. 

to make it work again
- kill FancyPlyces in TaskManager
- Switch on gps
- start FancyPlyces
  - ==> FancyPlyces gets gps-notification (gps-icon in status bar). 

Tested with 
- android-4.4 non-google device
- FancyPlyces-apk version from from ticket #7

**Comment by gabm** [comment]
You're right - its not being initialized - i will fix that...

Do you know if there is a callback, when new location-providers become available? (e.g. when the user switches on GPS)?

**Comment by k3b** [comment]
you can use the GpsStatus.Listener with the events GpsStatus.GPS_EVENT_STARTED and GpsStatus.GPS_EVENT_STOPPED . 

see http://developer.android.com/reference/android/location/GpsStatus.Listener.html for details

I havent tried this myself

**Comment by gabm** [comment]
better would be probably:

... implements LocationListener
@Override
public void onProviderEnabled(String provider) {  }

@Override
public void onProviderDisabled(String provider) { }

**Comment by gabm** [comment]
I made another debug build [here](https://www-user.tu-chemnitz.de/~gabm/FancyPlaces/FancyPlaces.apk) for you to test if the problem has been resolved...

**Comment by k3b** [comment]
sorry the new version does not solve the issue

this does NOT work
- kill app
- disable gps
- start app
- => no gps reception in app as expected
- enable gps
- => no gps reception (should get gps and show gps-icon)

this does work
- kill app
- enable gps
- start app
- => gps reception in app as expected
- disable gps
- => no gps reception in app as expected
- enable gps
- => again gps reception in app as expected

Here is some working sourcecode of SatStat that does not have this issue

https://github.com/mvglasow/satstat/blob/master/src/com/vonglasow/michael/satstat/MainActivity.java

SatStat is also available on fdroid-store and is my reference app with all things that have to do with gps

**Comment by gabm** [comment]
hmmm thats strange, i can do exactly the same thing and it works for me... please make sure that you are using the right version of the app (com.gabm.fancyplaces.debug) .. i will test on my android without play services this evening..

**Comment by k3b** [comment]
i have installed the app build on "2015-06-09 16:01" from this ticket. May be it is a good idea to add the versionnumber to the apps title or into the about-box so a tester can verify wich app version is running

**Comment by k3b** [comment]
I habe tested  the New Version in my android-4.2 non GPS Google.play device with the same evvect still dies not work if WLAN+location is disabled before APP starts i geht no location after enabling WLAN and location

**Comment by gabm** [comment]
ok, i see, i am able to reproduce your issue... i'll have a look, it seems onProviderEnabled doesnt get called..

EDIT: for reference: here is the reason why ... http://stackoverflow.com/questions/13848605/is-onproviderenabled-only-called-if-listener-registered-for-that-provider

**Comment by gabm** [comment]
Ok k3b - well i think i found a solution... have look at [this version](https://www-user.tu-chemnitz.de/~gabm/FancyPlaces/FancyPlaces.apk) .. i think it works...

P.S.: Debug Builds now have a DateString int the title :)

**Comment by k3b** [comment]
Problem solved :-) The new Version gehts the GPS on my two Android devices although gpx Export is gone. Thanks for the support

**Comment by gabm** [comment]
GPS export isn't finished yet and therefore will not be included in version 1.1.1... This bugfix will be :) Thanks for your help
